//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlamehProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cobone
    {
        public int Cobone_ID { get; set; }
        public string cobone_number { get; set; }
        public System.DateTime active_date { get; set; }
        public System.DateTime end_date { get; set; }
        public string status { get; set; }
        public string Products { get; set; }
        public int percent { get; set; }
    }
}
