//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlamehProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int Sold_Quantity { get; set; }
        public int Product_ID { get; set; }
        public int Invoice_ID { get; set; }
        public int PK { get; set; }
    
        public virtual invoice invoice { get; set; }
        public virtual product product { get; set; }
    }
}
